### ISSUE TITLE
Recommendation: AsciidocFX can have an easier out-of-the-box way to support the setup and use of CJK

### ISSUE THREAD

**Issue by life888888** [asciidocfx/asciidoctor-cjk-demo#1]
Use My asciidoctor-pdf-cjk-ext project (https://github.com/life888888/asciidoctor-pdf-cjk-ext)

Language Code:

- `tc` : Traditional Chinese
- `sc` : Simplified Chinese
- `hk` : Hong Kong
- `jp` : Japanese
- `kr` : Korean

## Type1: user jar file

Step1 Download  install-jar-to-libs-dir.sh (https://raw.githubusercontent.com/life888888/asciidoctor-pdf-cjk-ext/main/install-jar-to-libs-dir.sh
)
Step 2  execute If it is Japanese, the input parameter is `jp`, if it is Traditional Chinese , the input parameter is `tc`

` $ ./install-jar-to-libs-dir.sh tc`

It will download the jar to the libs subdirectory of your user home directory (`~/libs`)

Step 3 copy jar to AsciidocFX lib

`$ cp ~/libs/*.jar ~/TOOLS/AsciidocFX/lib
`
Step 4 Edit Config file  asciidoctor_pdf.json

Edit  `~/TOOLS/AsciidocFX/conf/asciidoctor_pdf.json`  or `~/.AsciidocFX-1.8.0/asciidoctor_pdf.json`
```json
{
	"backend": "pdf",
	"jsPlatform":"Asciidoctorj",
	"safe": "unsafe",
	"header_footer": true,
	"converter": "ASCIIDOCTOR",
	"attributes": {
                "pdf-fontsdir": "uri:classloader:/data/fonts;GEM_FONTS_DIR;",
                "pdf-themesdir": "uri:classloader:/data/themes",
                "pdf-theme": "default-ext-notosans-cjk-tc",	
		"showtitle": "true",
		"allow-uri-read": "true",
		"source-highlighter": "rouge",
		"icons": "font",
		"imagesdir": "images",
		"experimental": "true"
	}
}
```

## Type2: use file

https://github.com/life888888/asciidoctor-pdf-cjk-ext

Step1 Download  `install-zip-to-downloaded-resources-dir.sh` (https://raw.githubusercontent.com/life888888/asciidoctor-pdf-cjk-ext/main/install-zip-to-downloaded-resources-dir.sh)

Step 2  execute If it is Japanese, the input parameter is `jp`, If it is Simplified Chinese , the input parameter is `sc`

`$ ./install-zip-to-downloaded-resources-dir.sh sc`

It will download fonts and themes to the downloaded-resources subdirectory of your user home directory (`~/downloaded-resources`)

Step 3 Edit Config file  asciidoctor_pdf.json

Edit `~/TOOLS/AsciidocFX/conf/asciidoctor_pdf.json`  or `~/.AsciidocFX-1.8.0/asciidoctor_pdf.json`

```bash
{
	"backend": "pdf",
	"jsPlatform":"Asciidoctorj",
	"safe": "unsafe",
	"header_footer": true,
	"converter": "ASCIIDOCTOR",
	"attributes": {
                "pdf-fontsdir": "/home/demo/downloaded-resources/fonts;GEM_FONTS_DIR;",
                "pdf-themesdir": "/home/demo/downloaded-resources/themes",
                "pdf-theme": "default-ext-notosans-cjk-tc",	
		"showtitle": "true",
		"allow-uri-read": "true",
		"source-highlighter": "rouge",
		"icons": "font",
		"imagesdir": "images",
		"experimental": "true"
	}
}
```
## PDF Save
Then use AsciidocFX's PDF -> Save to save it as a CJK PDF file without the tofu box chars.

## Fonts
Supports Noto Sans CJK, Noto Sans Mono CJK, Noto Serif CJK fonts.

## Themes
Each font style supports 3 kinds of pdf-theme , please replace the following `tc` with the language code you want to use (`sc`,`hk`,`jp`,`kr`)

### Noto Sans CJK
- default-ext-notosans-cjk-tc
- default-notosans-cjk-tc
- notosans-cjk-tc

### Noto Sans Mono CJK
- default-ext-notosansmono-cjk-tc
- default-notosansmono-cjk-tc
- notosansmono-cjk-tc

### Noto Serif CJK
- default-ext-notoserif-cjk-tc
- default-notoserif-cjk-tc
- notoserif-cjk-tc

## AsciidocFX FOP
I also provide CJK Fonts for AsciidocFX using FOP converter
https://github.com/life888888/asciidocfx-pdf-cjk-patch

## Asciidoc file for CJK testing , you can get it from here

PDF-CJK-TEST_JP.adoc ( https://raw.githubusercontent.com/life888888/asciidoctor-pdf-cjk-ext-gradle-examples/main/pdf-cjk-ext-adocs-examples/src/docs/asciidoc/PDF-CJK-TEST_JP.adoc )

PDF-CJK-TEST_TW.adoc (https://raw.githubusercontent.com/life888888/asciidoctor-pdf-cjk-ext-gradle-examples/main/pdf-cjk-ext-adocs-examples/src/docs/asciidoc/PDF-CJK-TEST_TW.adoc)

PDF-CJK-TEST_CN.adoc (https://raw.githubusercontent.com/life888888/asciidoctor-pdf-cjk-ext-gradle-examples/main/pdf-cjk-ext-adocs-examples/src/docs/asciidoc/PDF-CJK-TEST_CN.adoc)

- Test: Display Chinese / Japanese fonts can display Regular, Bold, Italic, Bold Italic four styles normally.
- Test: Display special Unicode fonts, test Fallback settings 
- Test: Show emoji fonts

**Comment by rahmanusta** [comment]
Hi @life888888 , it is a really good work that you cover all CJK font necessities for the Asciidoctor PDF. AsciidocFX has a new feature called templates, and templates can automatically can be cloned from a git repository or from a zip file.

I created a CJK Template demo here: https://github.com/asciidocfx/Asciidoctor-CJK-Demo

This demo can be cloned by users from AsciidocFX by clicking right-click to any folder in tree.

![Image-211022-083457 535](https://user-images.githubusercontent.com/1158804/197128945-97983f36-b1b9-4090-ae99-a961424571af.png)


I think my demo is very simple and doesn't cover all the cases. What do you think if we just create CJK templates for each language and include it in AsciidocFX ?

Please see templates_config.json https://github.com/asciidocfx/AsciidocFX/blob/master/conf/templates_config.json which list current set of templates in AsciidocFX.

Kudos to @gillesB for bringing the idea and developing Templates.

**Comment by life888888** [comment]
1. Yes , Templates is good idea !

2. I guess not everyone want to play font and theme. 

They maybe just want to use AsciidocFX open their adoc file, PDF -> Save ,  View PDF Chinese Char is everything OK.

![DIFF](https://user-images.githubusercontent.com/101442875/197135303-81952ebe-4f7c-472d-91d8-9cd97918b7d5.png)
